### ISSUE TITLE
Request Presentation gives error

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-toolbox#210]
When creating a presentation request under the verification tab I get the error below. Starting from a proposal works fine

```
animo-acme-acapy_1   | 2021-06-08 20:58:18,532 aries_cloudagent.core.conductor ERROR DON'T shutdown on AttributeError 'IndyProofRequest' object has no attribute 'get'
animo-acme-acapy_1   | 2021-06-08 20:58:18,533 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
animo-acme-acapy_1   | Traceback (most recent call last):
animo-acme-acapy_1   |   File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/core/dispatcher.py", line 196, in handle_message
animo-acme-acapy_1   |     await handler(context, responder)
animo-acme-acapy_1   |   File "/home/indy/aries-acapy-plugin-toolbox/acapy_plugin_toolbox/util.py", line 216, in handle
animo-acme-acapy_1   |     return await func(context.message, context, responder)
animo-acme-acapy_1   |   File "/home/indy/aries-acapy-plugin-toolbox/acapy_plugin_toolbox/util.py", line 97, in _logged
animo-acme-acapy_1   |     return await func(*args)
animo-acme-acapy_1   |   File "/home/indy/aries-acapy-plugin-toolbox/acapy_plugin_toolbox/util.py", line 70, in _wrapped
animo-acme-acapy_1   |     return await func(*args)
animo-acme-acapy_1   |   File "/home/indy/aries-acapy-plugin-toolbox/acapy_plugin_toolbox/issuer.py", line 200, in handle
animo-acme-acapy_1   |     if not self.proof_request.get("nonce"):
animo-acme-acapy_1   | AttributeError: 'IndyProofRequest' object has no attribute 'get'
```

**Comment by dbluhm** [comment]
This should now be fixed with https://github.com/hyperledger/aries-acapy-plugin-toolbox/commit/0351abe4cd5088e9e3b196488155c1fa85ef401a
